import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import cn from 'classnames';

import Header from '@/app/_header';
import Footer from '@/app/_footer';
import MainWrapper from '@/app/MainWrapper';
import MainContentWrapper from '@/app/MainContentWrapper';

import './globals.scss';
import 'anityanhub-ui-lib/style.css';

const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Anityanhub',
  description: 'Generated by create next app',
  icons: {
    icon: './icons/ath-icon/android-chrome-512x512.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <MainWrapper>
          <MainContentWrapper>
            <Header />
            <main className={cn('main-content')}>{children}</main>
            <Footer />
          </MainContentWrapper>
        </MainWrapper>
      </body>
    </html>
  );
}
